### PR TITLE
xapian_wrap.cpp: fix language code checks for "zr-hant" and "sr-me"

### LINKED ISSUE #5118: xapian_wrap.cpp:detect_language() compares lower case string to mixed case string - this always fails
xapian_wrap.cpp:detect_language() first converts the value of the `code` variable to lower-case, then compares that value to `zh-Hant` and `sr-ME`.  This case-sensitive comparison always fails.

https://github.com/cyrusimap/cyrus-imapd/blob/58ffda28d50aea81fe53a52a766b3053d7fa6a05/imap/xapian_wrap.cpp#L398-L410

### PR DESCRIPTION
**Pull request by rsto**
These language code never were detected correctly, because they erroneously were compared lowercase against mixed-case strings.

Thanks to @dilyanpalauzov

Fixes #5118

### CODE REVIEW

File: imap/xapian_wrap.cpp [hunk 1]
```diff
@@ -399,10 +399,10 @@ static std::string detect_language(const struct buf *part)
         std::string code(CLD2::LanguageCode(lang));
         std::transform(code.begin(), code.end(), code.begin(), ::tolower);
         // Map CLD2 special codes to ISO 639.
-        if (!code.compare("zh-Hant")) {
+        if (!code.compare("zh-hant")) {
```
Comment (dilyanpalauzov) [inline imap/xapian_wrap.cpp:402]: I suggest `if (code == "zh-hant") {`.

Comment (rsto) [reply imap/xapian_wrap.cpp]: ack

**Review by ksmurchison — APPROVED** [review]

**Comment by dilyanpalauzov** [comment]
This can be easily backported.

**Comment by elliefm** [comment]
Don't know how far back this can go, labelling them all and I'll find out when I get there.
