### PR TITLE
tls: make sure saved session is refcounted

### LINKED ISSUE #3191: sync_client coredumps at RESTART
After configuring rolling replication from 3.2.3 to 3.2.3, replication works fine but I have 3 coredumps so far...

All of them seem related to TLS.
Openssl is 1.1.1h.

**Do "sync_client" works fine using TLS?**

The cores seem to happen after RESTART, this could seem related to #2979 but I don't think so.

The only log I see is this, even though I used debug:1 and "sync_client -v -v -l -r":
`Sep 24 22:08:12 local6:info sync_client: sync_client[32714]: sync_client RESTART succeeded`

I compiled without -g so the bt is poor. I have recompiled now with -g and waiting for a core.

```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f12ac370216 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f12ac370216 in raise () from /lib64/libc.so.6
#1  0x00007f12ac353536 in abort () from /lib64/libc.so.6
#2  0x00007f12ac3b9d46 in __libc_message () from /lib64/libc.so.6
#3  0x00007f12ac3c25ea in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f12ac3c3c2c in unlink_chunk.constprop () from /lib64/libc.so.6
#5  0x00007f12ac3c5cfc in _int_malloc () from /lib64/libc.so.6
#6  0x00007f12ac3c652f in _int_realloc () from /lib64/libc.so.6
#7  0x00007f12ac3c8306 in realloc () from /lib64/libc.so.6
#8  0x00007f12ac918c2a in OPENSSL_sk_insert () from /usr/lib64/libcrypto.so.1.1
#9  0x00007f12aca4c923 in SSL_get1_supported_ciphers () from /usr/lib64/libssl.so.1.1
#10 0x00007f12aca599f8 in tls_construct_ctos_ec_pt_formats () from /usr/lib64/libssl.so.1.1
#11 0x00007f12aca590c2 in tls_construct_extensions () from /usr/lib64/libssl.so.1.1
#12 0x00007f12aca62c67 in tls_construct_client_hello () from /usr/lib64/libssl.so.1.1
#13 0x00007f12aca6205f in state_machine.part () from /usr/lib64/libssl.so.1.1
#14 0x00007f12acd080a0 in tls_start_clienttls () from /usr/lib64/libcyrus_imap.so.0
#15 0x00007f12acc9e80b in backend_starttls () from /usr/lib64/libcyrus_imap.so.0
#16 0x00007f12acc9ef72 in backend_login () from /usr/lib64/libcyrus_imap.so.0
#17 0x00007f12acca0134 in backend_connect () from /usr/lib64/libcyrus_imap.so.0
#18 0x000000000040850f in replica_connect ()
#19 0x000000000040678a in main ()
```

```
Reading symbols from /usr/sbin/sync_client...
(No debugging symbols found in /usr/sbin/sync_client)
[New LWP 24805]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/sync_client -r'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ff3b024ee3c in free () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ff3b024ee3c in free () from /lib64/libc.so.6
#1  0x00007ff3b08dbf4e in SSL_SESSION_free () from /usr/lib64/libssl.so.1.1
#2  0x00007ff3b08dc2d6 in ssl_get_new_session () from /usr/lib64/libssl.so.1.1
#3  0x00007ff3b08e9872 in tls_construct_client_hello () from /usr/lib64/libssl.so.1.1
#4  0x00007ff3b08e905f in state_machine.part () from /usr/lib64/libssl.so.1.1
#5  0x00007ff3b0b8f0a0 in tls_start_clienttls () from /usr/lib64/libcyrus_imap.so.0
#6  0x00007ff3b0b2580b in backend_starttls () from /usr/lib64/libcyrus_imap.so.0
#7  0x00007ff3b0b25f72 in backend_login () from /usr/lib64/libcyrus_imap.so.0
#8  0x00007ff3b0b27134 in backend_connect () from /usr/lib64/libcyrus_imap.so.0
#9  0x000000000040850f in replica_connect ()
#10 0x000000000040678a in main ()
(gdb)
```

```
(gdb) bt
#0  0x00007f2b2a511216 in raise () from /lib64/libc.so.6
#1  0x00007f2b2a4f4536 in abort () from /lib64/libc.so.6
#2  0x00007f2b2a55ad46 in __libc_message () from /lib64/libc.so.6
#3  0x00007f2b2a5635ea in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f2b2a564c2c in unlink_chunk.constprop () from /lib64/libc.so.6
#5  0x00007f2b2a566cfc in _int_malloc () from /lib64/libc.so.6
#6  0x00007f2b2a56752f in _int_realloc () from /lib64/libc.so.6
#7  0x00007f2b2a569306 in realloc () from /lib64/libc.so.6
#8  0x00007f2b2aab9c2a in SRP_create_verifier () from /usr/lib64/libcrypto.so.1.1
```

### PR DESCRIPTION
**Pull request by elliefm**
otherwise OpenSSL will eventually garbage collect it out from under us, causing a crash when we try to reuse it.  Also free it properly when we're done with it.

Same also for imtest.

Fixes #3191, and maybe #2979

### CODE REVIEW

**Review by ksmurchison — APPROVED** [review]
Looks sane

File: imap/tls.c [hunk 1]
```diff
@@ -1684,11 +1684,21 @@ HIDDEN int tls_start_clienttls(int readfd, int writefd,
...
         r = -1;
         goto done;
     }
-    if (sess) *sess = SSL_get_session(tls_conn);
+
+    /* Session may have been renegotiated; make sure we cache the right one */
+    if (sess) {
+        if (*sess)
+            SSL_SESSION_free(*sess);
+        *sess = SSL_get1_session(tls_conn);
```
Comment (brong) [inline imap/tls.c:1700]: Yeah right, this one adds the refcount :) https://www.openssl.org/docs/man1.1.0/man3/SSL_get1_session.html

**Review by brong — APPROVED** [review]
Yeah, looks great.  Much better to manage it properly.
